### PR TITLE
initial gh actions config for running unit tests

### PR DESCRIPTION
**Pull request by m1yag1**

### CODE REVIEW

**Review by rnathuji — COMMENTED** [review]
Very cool! I did notice the new config doesn't incorporate the `pep8` linting from the older travis steps. Was that on purpose?

**Comment by m1yag1** [comment]
oh good catch! that was not on purpose. I got ahead of myself. i was too excited.

**Comment by m1yag1** [comment]
i'll add that now.

**Review by rnathuji — APPROVED** [review]
Much faster than Travis! 😃

**Comment by m1yag1** [comment]
@rnathuji I added the linting step you noticed was missing. On another note, mock should be installed already in the python 2.7 run but it wasn't for some reason. That's why I've added now and doesn't seem to affect the 3.6 env either. I debated removing python 2.7 as we don't run it in production. What do you think?

**Comment by rnathuji** [comment]
Isn't publishing still on python2? It has `cnx-epub` as a dependency.

**Comment by m1yag1** [comment]
Oh you know what i'm getting my wires crossed 😅 . I've been working on cnx-press in cnx-deploy and was thinking of cnx-press. disregard my last.

**Pull request merged**
